
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.3'
version_full = '3d12eecc94cb6bbaf36e736082355c3006942608'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

